# Generated by Django 3.0.5 on 2020-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('death', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('quarantine', models.IntegerField()),
            ],
        ),
    ]
