# Generated by Django 3.0.5 on 2020-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictwiseCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=100)),
                ('Confirmed_Positive_Cases', models.IntegerField()),
                ('Cases_Tested', models.IntegerField()),
                ('Patients_Recovered', models.IntegerField()),
                ('People_Under_Quarantine', models.IntegerField()),
                ('Total_Deaths', models.IntegerField()),
            ],
        ),
    ]
